### ISSUE TITLE
Add new ML models

### ISSUE THREAD

**Issue by lmacielvieira** [metaspace2020/metaspace#1491]
### Description
It is necessary to update the ML models in M\ that were trained as part of the work on the article.

### Steps

- [ ] Change text in the analysis version tooltip (upload page) with bio archive reference and new models. It is also necessary to add an explanation of which model is better to choose for samples that are not animals or plants [Bishoy]
- [ ] Replace the changed text in the source code. Don't forget the same for vue 3.0 [Lucas]
- [x] Rename ML models to v2.<date> instead of v3 [Sergii]
- [ ] Add new ML models in M\ (S3 bucket and import) [Sergii]
- [ ] Add README to the previous ML model's in github page (and list of test/train datasets) [Sergii/Bishoy]

**Comment by Bisho2122** [comment]
- [ ] Change text in the analysis version tooltip (upload page) with bio archive reference and new models. It is also necessary to add an explanation of which model is better to choose for samples that are not animals or plants [Bishoy]
- [ ] Replace the changed text in the source code. Don't forget the same for vue 3.0 [Lucas]
- [ ] Rename ML models to v2. instead of v3 [Sergii]
- [ ] Add new ML models in M\ (S3 bucket and import) [Sergii]
- [X] Add README to the previous ML model's in github page (and list of test/train datasets) [Sergii/Bishoy]
