### ISSUE TITLE
Updated projects page design

### ISSUE THREAD

**Issue by Ren22** [metaspace2020/metaspace#155]
1. Updated
![screenshot from 2018-11-27 14-32-50](https://user-images.githubusercontent.com/13621309/49085643-c1f37c80-f252-11e8-9a61-2553b7c593bf.png)
2. Experimental 
![screenshot from 2018-11-27 14-23-36](https://user-images.githubusercontent.com/13621309/49085644-c28c1300-f252-11e8-88fa-87e5bfc5d239.png)

I haven't submitted PR yet, it's in progress. my motivation to these design tweaks are to 
1) give more space between elements as otherwise it looks overloaded
2) get rid of the intuitive text on experimental version and leave only icons (such as delete proj and etc), assisting message still appears when hovering
3) add more indents for better formatting
4) substitute padlock icon with a bit modern one and move it next to the project's name as it's not related to the actions

**Comment by Ren22** [comment]
@theodev  @intsco @LachlanStuart 
your feedback (if you have time) is welcomed

**Comment by LachlanStuart** [comment]
I like the slightly larger indentation of the informational lines vs the name. It helps to guide the eyes to the right place.

I suggest we don't add managers' groups as it's not so easy to do. At the moment only admins can see other users' `primaryGroup`. Even if we changed that, the `primaryGroup` is not necessarily accurate - people may be making a project on behalf of a non-primary group, or their `primaryGroup` may not have even accepted their request to join.

Regarding design 2, I think we should avoid having icon-only interfaces if we have space to have text buttons. Icon-only buttons tend to not be very user-friendly. Imagine if you were unfamiliar with METASPACE and you saw this:
![image](https://user-images.githubusercontent.com/26366936/49087141-7e9b0d00-f256-11e8-81ea-481bdc0ded9e.png)
How long would it take you to figure it out? Because with text it's almost instant.

I like the addition of color for "4 Datasets". I wonder if we should make the project manager names link to a filtered version of the datasets page, just so we can add some more color...

**Comment by Ren22** [comment]
@LachlanStuart Thank you for the feedback.
Ah, that explains now why I couldn't see projects anymore when I wasn't a superadmin. Apparently, it got broken because of pulling `primaryGroup`. It was asked by Theo though, I'll try to find a way when I have some time how to do it then.
For the design 2 - do you think it will be easier for a user when there's a popping up text when hovering over the icon? 2 of them I think quite intuitive(edit/delete) 
 
![screenshot from 2018-11-27 17-18-15](https://user-images.githubusercontent.com/13621309/49095418-b7dc7880-f268-11e8-9bae-832be4312c00.png)

**Comment by LachlanStuart** [comment]
> For the design 2 - do you think it will be easier for a user when there's a popping up text when hovering over the icon?

No. I don't think we can make an intuitive icon for every action, and I think people will get frustrated if they have to hover over buttons to find out what they mean. I've gotten annoyed at several sites because of this. It can be OK if you've got really good icon design and all the actions are things that people would intuitively think to do, but the actions we have, particularly "Browse annotations" and "Show full metadata", don't meet either criteria.

I don't want to make a significant change for this page without giving consideration to how we'll update the datasets page. Consistency in design is important. Inconsistent sites feel bad no matter how good individual parts of it may be.

Are you aware that most users will only see the "Browse annotations" button against projects? So for most projects there would be just one icon, which IMO would be a bit awkward. That could be changed though - there are technically 3 actions exposed here: View project page (clicking on title), Browse datasets (clicking on 4 Datasets), Browse annotations.
