### ISSUE TITLE
Fix database date handling

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#578]
Dataset.upload_dt and Dataset.status_update_dt are stored as local datetimes, with no explicit timezone.

Project.created_dt is stored as a UTC datetime, with no explicit timezone.

Three possible solutions:
1. Fix the values in Project.created_dt, and ensure that all places that set date values (including the database default values) are in the local timezone
2. Switch to the `TIMESTAMP WITH TIME ZONE`/`TIMESTAMPTZ` datatype so that we can have UTC everywhere (presumably). The behavior of this is still unclear and needs more testing
3. Switch to UTC timestamps without timezones and change our DB drivers to interpret them as UTC, e.g.
```
import * as pg from 'pg'

// https://github.com/typeorm/typeorm/issues/4519#issuecomment-606319943
// all `Date`s should be assumed to be in UTC when being sent to Postgres
pg.defaults.parseInputDatesAsUTC = true;
// all dates received from Postgres should be assumed to be UTC when converted to `Date`s
const TIMESTAMP = '1114' // https://github.com/brianc/node-pg-types/blob/master/lib/builtins.js#L47
pg.types.setTypeParser(TIMESTAMP, (stringValue: string) => new Date(`${stringValue}Z`));
```

One approach should be chosen and the data fixed.

**Comment by intsco** [comment]
>**lachlan** No, we haven't done anything. We chose an option that isn't listed there: always generate dates/times in code instead of SQL. It doesn't matter what timezone Postgres thinks the server is in, because psycopg2 and TypeORM have the same conversion behavior. TypeORM and psycopg2 consistently read/write the dates as if Postgres was storing them in the local datetime.

>The main issue with this is that Postgres has its own timezone setting, which may be different to the system timezone. Also timezone can be set for each connection, but I can't remember if psycopg2/TypeORM do this.
If Postgres generates a date for the current time, in some situations (e.g. inside Docker) where it will make a time in the wrong timezone. I think Option 2 in that issue is the only way where we could make Postgres, TypeORM and psycopg2 all behave identically, because they all seem to treat TIMESTAMPTZ as UTC even though I think that's an unofficial specification and not part of the SQL spec.

>Oh, actually, I did do Option 1 to make Project.created_dt consistent with the other datetimes. The fix is in graphql/migrations/1587990178565-FixDateColumns.ts. I think we kept that issue open to track it because we wanted Option 2 long-term

>moment.local() vs moment.utc() doesn't affect how the input is interpreted - all `Date`s in JS are stored in UTC but stringify to local time. Those two functions control which timezone Moment associates with the resulting variable, because Moment keeps a timezone with each value

>i.e.
```
date = new Date();
console.log(date) // 2020-12-01T16:07:19.599Z
console.log(moment.utc(date).format()) // 2020-12-01T16:07:19Z
console.log(moment(date).format()) // 2020-12-01T17:07:19+01:00
```
>All 3 are the same point in time, but the 3rd one has a local timezone
(moment.local() doesn't exist - I forgot it was just moment() for that behavior)

>Also, I guess I was wrong about "all `Date`s in JS ... stringify to local time". It seems to only be when you do .toString() that they are printed in the local time:
date.toString() // -> 'Tue Dec 01 2020 17:07:19 GMT+0100 (Central European Standard Time)'

>Postgres stores them in some unknown timezone.
Postgres does some conversion on the way out, so the values it gives to TypeORM are in Local timezone (but not explicitly specified with the value).
TypeORM interprets them as Local, converts them to JavaScript `Date`s, which are always UTC and cannot be given a timezone (you can only specify a timezone when converting to string).
MomentValueTransformer converts them to Moments, which can have any timezone, but in this case we say we want UTC instead of Local.
In every GraphQL resolver we use .toISOString(). Because we chose UTC instead of Local, the string has a Z on the end (meaning it's UTC). If we used Local, it wouldn't have a Z and that would cause problems if the server was in a different TZ to the browser.

After a discussion with @LachlanStuart, we decided to close this issue. The discussion is cited above.
