### ISSUE TITLE
Migrate image storage to S3

### ISSUE THREAD

**Issue by intsco** [metaspace2020/metaspace#697]
TODO:
- [x] Update Ansible configs for all environments.
- [x] Migrate images: copy files from local FS to S3, map to new S3 paths.
- [x] Migrate ES index: add new `iso_image_urls` field.
- [x] Migrate database data: optical images and thumbnail urls.
- [ ] Remove `img_service_url` and `img_service_public_url` from engine configs.

**Comment by LachlanStuart** [comment]
Related points to discuss:
* Can we group images by dataset, e.g. with directories?
* Should we use consistent filenames based on e.g. the hash of the image data or the ion formula, so that isomers / duplicated annotations between databases aren't duplicated?
* Can we structure the directory structure somehow so that diagnostic images fit neatly?

I'd love to also suggest switching image format, because PNG is actually really inefficient for these images, but there aren't any good options for 16-bit lossless right now :disappointed: . FLIF was the leading contender, but they have deprecated themselves in anticipation of JPEG XL, which isn't actually out yet (expected to release in 2021).
