### ISSUE TITLE
Make dataset editable by group

### ISSUE THREAD

**Issue by sergii-mamedov** [metaspace2020/metaspace#776]
At the moment, editing the dataset (changing metadata, loading optical images, ...) is available only to the owner of the dataset.
Increasingly, there is a need to be able to edit a dataset by multiple users. Alternatively, the following strategy is proposed:

1. All the same, the dataset will have one owner.
2. The owner can "share" the dataset within his own group (primary?) only.
3. Deleting the dataset, as before, will be possible only by the owner.
4. Also make the PI a co-owner (per #693 )

At the frontend level, an action `Share dataset with group` is required.
At the GraphQL level, we will need:
 - a new endpoint that will accept a request from the frontend and change the status of the dataset (an additional column in the table?)
 - additional logic that will check whether the user has permission to edit the dataset, as belonging to the same groups as the owner of the dataset.

**Comment by LachlanStuart** [comment]
Instead of an action (we try to minimize stand-alone actions, as they increase UI and API complexity), I see this as being an additional boolean input when creating/editing a dataset, in this section of the form:
![image](https://user-images.githubusercontent.com/26366936/109825892-91bd9400-7c3a-11eb-9702-a357cca81d19.png)

This would mean that logically it would just be a new field against the existing `DatasetCreateInput`/`DatasetUpdateInput` graphql types, handled by the existing `createDataset`/`updateDataset` mutations.

There would also need to be logic so that only the submitter is allowed to edit this field.

The UI also needs to know "Am I allowed to edit this dataset?" to decide whether to the edit/delete/etc. buttons. Currently this is hard-coded as `dataset.submitter.id === currentUser.id`, but it would be best if graphql directly gave this information so that the webapp doesn't need duplicate logic. I would suggest adding `canEdit` and `canDelete` fields to the `Dataset` graphql resolver, so that the UI can use those (there is already a `canDownload`).
