### ISSUE TITLE
Ds comparison page improvements after first feedback

### ISSUE THREAD

**Issue by lmacielvieira** [metaspace2020/metaspace#883]
In order to improve the ds comparison page, some small features should be added.

- [ ] The user should be able to select the datasets to be compared from the dataset list page
- [ ] Add m/z value into the annotation table
- [ ] Add  a popup explaining which MSM is shown in the annotations table
- [ ] Show individual MSM next to each dataset/image, next to its intensity
- [ ] Add a link for each image (annotation within individual dataset) that can be clicked and open the annotation within the selected dataset in a regular view
- [ ] Fix export to CSV

**Comment by LachlanStuart** [comment]
Bug fixes:
- [ ] Fix the default sort order (should be FDR ascending, then MSM descending)
- [ ] Fix the colorization of zero-intensity pixels. On Staging they're showing up as transparent - ion images should only have transparency when there's an optical image.
- [ ] Fix the positioning of the intensity popup when hovering over the image in Firefox

UX changes:
- [ ] Only show a single "cog menu" (intensity scaling, colormap, scale bar color) that affects all images simultaneously
- [ ] Show the name of each dataset above their image so that it's possible to tell them apart if you don't remember how you arranged the grid

I'd expect scientists to want to compare the molecules between datasets in tabular form, so that they don't need to open each annotation and look at all the images one-by-one. However, showing it all at once would be too many columns to display by default, so it'd need to be customizable by the user.
- [ ] Allow user to select a field (MSM, FDR, maxIntensity or totalIntensity) to show in the table with one column per dataset.
- [ ] For dataset-specific fields, show a separate column for each dataset in the CSV (i.e. if you have 5 datasets, then the CSV should have 5 `minIntensity` columns, 5 `maxIntensity` columns, etc.

One suggestion that IIRC came from GM:
- [ ] Ability to filter and/or sort by the number of datasets that include an annotation, so that users can easily see molecules that are shared and/or not shared

Additionally, I'd suggest changing the "Add a popup explaining which MSM is shown in the annotations table" task - IMO the issue isn't that it's unclear which dataset it comes from. The issue is that showing the MSM for the first non-null annotation just isn't very useful, because there's multiple values and instead of summarizing them, one is being arbitrarily picked. I think people would find it more useful to see the best value out of the datasets.
- [ ] Change the MSM/FDR columns to consistently show the best value (highest MSM / lowest FDR) out of the datasets. Also rename them to "Best MSM" / "Best FDR" to reflect this.
- [ ] Additionally, allow Best MSM/Best FDR to be used for filtering or sorting, because most users will still want to compare images if an annotation has e.g. 5% FDR in one dataset and 50% in another.  (Talk to Veronika if you want more information about this use-case, as she has tried to use METASPACE for dataset comparison in the past, and ran into this inconsistent FDR issue every time)
