### ISSUE TITLE
Ion images not shown

### ISSUE THREAD

**Issue by paoloinglese** [metaspace2020/metaspace#987]
Hi! I've installed metaspace locally using the docker instructions. Everything seems to work fine, except that when I select an annotated mass, the corresponding ion image is not shown in the right panel. Is this expected in the dev environment or I'm doing something wrong?

Many thanks!

**Comment by LachlanStuart** [comment]
Hi @paoloinglese ,

I think the most likely cause is that the default config tries to serve the ion images from `http://storage:9000`, but the `storage` server name is only automatically set up inside the Docker network and needs to be manually configured to access server from your browser. We switched to using this Docker-based storage server after making the Docker setup instructions, so it's likely that we just forgot to add instructions to work around this.

The fix to this is to make a mapping on your local computer so that the `storage` domain name points to the same IP address as `localhost` so that the port 9000 requests go to Docker. You can do this by adding the following line to the hosts file (at `/etc/hosts` on Linux/Mac and `C:\windows\system32\drivers\etc\hosts` on Windows):
```
127.0.0.1    storage
```

**Comment by paoloinglese** [comment]
Hi @LachlanStuart ,

I've tried that but unfortunately it still cannot load the ion images. I can access the storage through `http://localhost:9000` and `http://storage:9000` using the default user and password for MinIO.

**Comment by paoloinglese** [comment]
I've reinstalled it and now it works! Thanks a lot! :)
