### ISSUE TITLE
[AnnotationTable] Make annotation table columns customizable

### ISSUE THREAD

**Issue by lmacielvieira** [metaspace2020/metaspace#990]

**Comment by LachlanStuart** [comment]
To help with planning this, here's my wishlist for improvements to the Annotations table. This doesn't all have to be implemented as part of this task, I'm just listing ideas I've had over the years.

* Ability to add columns: 
    * Molecules (comma-separated list of names)
    * Database
    * Max intensity
    * Total intensity
    * Adduct (separately from the formula so that it can be used for sorting, or so that you can see the molecule name and adduct without the formula taking up space)
    * Spatial/Spectral/Chaos metrics
    * On-/Off-sample
    * If isomers/isobars are present (Just a column that's usually empty but shows a caution icon for molecules with isomers/isobars)
* Ability to hide each existing column
* Ability to adjust the size of the table so that the image view gets more screen space (e.g. with a draggable divider), or even hide the annotations table completely
